apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: artifact-keeper

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - pvc.yaml
  - hpa.yaml
  - backup-cronjob.yaml
